# Generated by Django 2.0.7 on 2018-07-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_title',
            new_name='title',
        ),
    ]
