# Generated by Django 2.0.7 on 2018-07-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180725_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_content',
            new_name='content',
        ),
    ]
